### ISSUE TITLE
DevOps: As a developer, I want a distribution folder with pre-compiled executables

### ISSUE THREAD

**Issue by kiddliu** [JingJingJingJing/Sira#83]
As a developer, I want a 'dist' folder to save all pre-compiled Sira executables, with name in format 'Sira-version-hash.exe'

**Comment by JingJingJingJing** [comment]
@kiddliu 
As far as I spiked, it's impossible to reduce the size of executable files.
Is it accptable to push executables whose size is about 10MB to git?

**Comment by kiddliu** [comment]
@JingJingJingJing no, I'll close this issue for now. Let's figure out if there's still another way to do it.
